In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
import csv
data = pd.read_csv('dataset.csv')
data.set_index ('Id',inplace = True)
import matplotlib.pyplot as plot

In [3]:
data.drop('Company', axis = 1, inplace= True)
less = data.iloc[1:10]
less.head()

Experience  php  python  qa  js  qualification  level  age
Id                                                             
2.0         4.0    0       0   0   1              2      3    5
3.0         4.0    0       1   0   0              2      3    3
4.0         4.0    0       0   1   0              2      3    4
5.0         1.0    1       0   0   0              3      2    2
6.0         4.0    1       0   0   0              3      3    1

In [4]:
A = less.iloc[1].values
B = less.iloc[2].values

In [5]:
A

array([ 4.,  0.,  1.,  0.,  0.,  2.,  3.,  3.])

In [25]:
ab=np.dot(A,B)

In [26]:
a=np.linalg.norm(A)

In [27]:
b=np.linalg.norm(B)

In [28]:
ab/(a*b)

0.96799393753226559

# KNN implementation

In [90]:
import pandas as pd
import numpy as np
import math
import operator

In [135]:
def cosdist (A,B):
    ab=np.dot(A,B)
    print('ab',ab)
    a=np.linalg.norm(A)
    print("a",a)
    b=np.linalg.norm(B)
    print("b",b)
    return (ab/(a*b))

In [140]:
cosdist( [1,2,3],[1,4,2])

ab 15
a 3.74165738677
b 4.58257569496


0.87481776527970656

In [122]:
def eucldist(A,B):
    a=0
    for i in range(len(A)):
        a += pow((A[i]-B[i]),2)
    a = math.sqrt(a)
    return a


In [123]:
def neighbours(train,test):
    difference=[]
    for each in train:
        distance = eucldist(each,test)
        difference.append((each,distance))
        difference.sort(key =operator.itemgetter(1))
    print(difference)

In [124]:
neighbours(train,[3,1,1])

[([1, 1, 3], 2.8284271247461903), ([1, 1, 4], 3.605551275463989)]


In [125]:
def neighbours(train,test):
    difference=[]
    for each in train:
        distance = cosdist(each,test)
        difference.append((each,distance))
        difference.sort(key =operator.itemgetter(1))
    print(difference[1])

In [126]:
neighbours(train,[3,1,1])

a 3.31662479036
a 4.24264068712
([1, 1, 3], 0.63636363636363635)


In [127]:
train = [[1,1,3],[1,1,4],[3,1,1]]
from sklearn.metrics import pairwise_distances, euclidean_distances

In [128]:
cosine_dist = pairwise_distances(train, metric='cosine')

In [129]:
print(cosine_dist)

[[ 0.          0.00506332  0.36363636]
 [ 0.00506332  0.          0.43146476]
 [ 0.36363636  0.43146476  0.        ]]
