In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
import csv

In [2]:
test1 = {'Experience':2 ,'php':1 ,'python':0 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3}
test1 = pd.DataFrame.from_dict([test1])
test2 = {'Experience':2 ,'php':0 ,'python':1 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3}
test2 = pd.DataFrame.from_dict([test2])

In [3]:
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")
pearson_sim = 1-pairwise_distances(test1,test2, metric="correlation")

In [4]:
cosine_sim

array([[ 0.94444444]])

In [5]:
pearson_sim

array([[ 0.88709677]])

In [6]:
test1 = {'php':1 ,'python':0 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3, 'Experience':2}
test1 = pd.DataFrame.from_dict([test1])
test2 = {'php':0 ,'python':0 ,'qa':0 ,'js':1 ,'qualification':2, 'level':3,'Experience':2 }
test2 = pd.DataFrame.from_dict([test2])

In [7]:
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")
pearson_sim = 1-pairwise_distances(test1,test2, metric="correlation")

In [8]:

cosine_sim

array([[ 0.94444444]])

In [9]:
pearson_sim

array([[ 0.88709677]])

In [31]:
test1 = {'php':1 }
test1 = pd.DataFrame.from_dict([test1])
test2 = {'php':3 } 
test2= pd.DataFrame.from_dict([test2])
cosine_sim = 1-pairwise_distances(test1,test2, metric="minkowski")

In [32]:
test1


php
0    1

In [33]:
test2

php
0    3

In [34]:
cosine_sim

array([[-1.]])