In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
import csv

In [2]:
test1 = {'Experience':2 ,'php':1 ,'python':0 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3}
test1 = pd.DataFrame.from_dict([test1])
test2 = {'Experience':2 ,'php':0 ,'python':1 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3}
test2 = pd.DataFrame.from_dict([test2])

In [3]:
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")
pearson_sim = 1-pairwise_distances(test1,test2, metric="correlation")

In [4]:
cosine_sim

array([[ 0.94444444]])

In [5]:
pearson_sim

array([[ 0.88709677]])

In [70]:
test1 = {'php':1 ,'python':0 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3, 'Experience':2}
test1 = pd.DataFrame.from_dict([test1])
test2 = {'php':0 ,'python':0 ,'level':3,'Experience':2 }
test2 = pd.DataFrame.from_dict([test2])

In [71]:
test1


Experience  js  level  php  python  qa  qualification
0           2   0      3    1       0   0              2

In [72]:
test2

Experience  level  php  python
0           2      3    0       0

In [73]:
missing = list(set(test1)-set(test2))
for each in missing:
    test2[each]=0

['qa', 'qualification', 'js']

In [75]:
test2

Experience  level  php  python  qa  qualification  js
0           2      3    0       0   0              0   0

In [49]:
a=pd.merge(test1,test2)

In [50]:

for each in a.loc[0]:
    if not a.empty:
        a[each]=test2[each]
    else:
        a[each]=0

KeyError: 'the label [0] is not in the [index]'

In [35]:
a

Empty DataFrame
Columns: [Experience, js, level, php, python, qa, qualification]
Index: []

In [7]:
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")
pearson_sim = 1-pairwise_distances(test1,test2, metric="correlation")

In [8]:

cosine_sim

array([[ 0.94444444]])

In [9]:
pearson_sim

array([[ 0.88709677]])

In [31]:
test1 = {'php':1 }
test1 = pd.DataFrame.from_dict([test1])
test2 = {'php':3 } 
test2= pd.DataFrame.from_dict([test2])
cosine_sim = 1-pairwise_distances(test1,test2, metric="minkowski")

In [32]:
test1


php
0    1

In [33]:
test2

php
0    3

In [34]:
cosine_sim

array([[-1.]])