In [17]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
import csv

In [24]:
test1 = {'Experience':2 ,'php':1 ,'python':0 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3}
test1 = pd.DataFrame.from_dict([test1])
test2 = {'Experience':2 ,'php':0 ,'python':1 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3}
test2 = pd.DataFrame.from_dict([test2])

In [25]:
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")
pearson_sim = 1-pairwise_distances(test1,test2, metric="correlation")

In [26]:
cosine_sim

array([[ 0.94444444]])

In [27]:
pearson_sim

array([[ 0.88709677]])

In [21]:
test1 = {'php':1 ,'python':0 ,'qa':0 ,'js':0 ,'qualification':2, 'level':3, 'Experience':2}
test1 = pd.DataFrame.from_dict([test1])
test2 = {'php':0 ,'python':0 ,'qa':0 ,'js':1 ,'qualification':2, 'level':3,'Experience':2 }
test2 = pd.DataFrame.from_dict([test2])

In [22]:
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")
pearson_sim = 1-pairwise_distances(test1,test2, metric="correlation")

array([[ 0.94444444]])

In [28]:

cosine_sim

array([[ 0.94444444]])

In [29]:
pearson_sim

array([[ 0.88709677]])

In [39]:
test1 = {'php':1 }
test1 = pd.DataFrame.from_dict([test1])
test2 = {'php':0 } 
test2= pd.DataFrame.from_dict([test2])
cosine_sim = 1-pairwise_distances(test1,test2, metric="cosine")

In [40]:
test1


php
0    1

In [41]:
test2

php
0    0

In [42]:
cosine_sim

array([[ 0.]])